# Rosalind: Transcribing DNA into RNA
# Converts a DNA sequence to RNA by replacing every T with U

def transcribe(sequence):
    result = ""
    for base in sequence:
        if base == "T":
            result = result + "U"
        else:
            result = result + base
    return result

sequence = "AAGTAGCCCATATAATCGCGTTACCAGCACGTGGAATCATTCGCTTAATAAAGGTTTACTGCAGAAAGGCGCGTGTACAACAGCCATAATTTTTACCCGAGTGCAAGCAAGACTGTGGCCTTGCCACTCGAGCTTTGATGGTCTAGCAGTAGATGTAGTTTTAAATCTTAAAGTGAGCAGTTTTAACAGCTACGTTTTCGCTCGGGTTTATAGCATCTTACGGAGCCGGGTTGAGTTGACACTCTACTTGATGCGAAGCTTCTATCGCACGGCCCTTGCCGTGCAAATGTATGTGCCGGACGATCGACCGTACGCCAACTAGTGCTGGGTTTACCAGCGGACCTCTCCCTGAAGGGCATAGCTCCTGGCGGGTCGTAGCGAATTAAGCTGCCTCCACATTTGCATACAACTCTTGTTTCGGTCCTGACTAAATTGCCGTGACGACAAGCGTTCACTAGACGCATTAGGAGGTTTTGGGCAAGCGCCAAAGTTAGAAAGACGTAGACAGATCCTAACTTGATCATCCAAGAATAAGGGGACTCAGTACGTAAGGCAAAACTAGGCCCAGGGGTTGATAACGGAAGGCCACGTCTAGCGATCATGTAGCTTCCGCACGATTAGGCAAAAAGGGTTGTTTTAATATAGACGCGTGGTTGTACGTTCTTCTAATAAGTGTGGTCAGATACACAGTGTTGGTCTCGACCGAAGTCTATTTGGCGGACCTAGGGTCGTCTGTGGCTTTACTCACGACTTAGATCAGAAAGCAACAAGATGAGCTAGCAATTTGCGCGTTGAGGTGTGATTAACCCGTTGCAAAACATGGCTAAATGCATGGCGCGTGAGCTAAAAACCAGCTAGACTGTATGTGTTCCTGCGGCGAGGCCGTCCGTGTAGTTTATACTAGGTGAGAGTGGACGTCCGCAAGGAGGGCTTCCCAGTATGGCTAA"
print(transcribe(sequence))